### ISSUE TITLE
Remove inspection on the main args.

### ISSUE THREAD

**Issue by aristotll** [stylismo/nullability-annotations-inspection#9]
<img width="434" alt="2017-10-02 11 08 48" src="https://user-images.githubusercontent.com/13341544/31063038-24b9bb50-a762-11e7-89da-7a69d4ddcbe8.png">

This `args` in main method cannot be null (it is final),  so is it better to ignore it?

**Comment by yborovikov** [comment]
Nothing stops anyone from passing a `null` argument to a `final` parameter.
